# Generated by Django 3.0.7 on 2020-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0003_auto_20200625_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
