# Generated by Django 3.0.8 on 2020-07-03 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0006_auto_20200625_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitInduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_induk', models.CharField(choices=[('uiw mmu', 'UIW Maluku dan Maluku Utara'), ('uip maluku', 'UIP Maluku')], max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitLayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitPelaksana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('unit_pelaksana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitInduk')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='lokasi_unit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Organisasi',
        ),
        migrations.AddField(
            model_name='unitlayanan',
            name='unit_layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitPelaksana'),
        ),
    ]
