# Generated by Django 3.0.8 on 2020-07-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0007_auto_20200703_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlayanan',
            name='unit_pelaksana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitPelaksana'),
        ),
        migrations.AddField(
            model_name='unitpelaksana',
            name='unit_induk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitInduk'),
        ),
        migrations.AlterField(
            model_name='unitinduk',
            name='unit_induk',
            field=models.CharField(choices=[('UIW MMU', 'UIW Maluku dan Maluku Utara'), ('UIP MALUKU', 'UIP Maluku')], max_length=255),
        ),
        migrations.AlterField(
            model_name='unitlayanan',
            name='unit_layanan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitpelaksana',
            name='unit_pelaksana',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
