# Generated by Django 3.0.8 on 2020-07-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0008_auto_20200703_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlayanan',
            name='unit_induk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitInduk'),
        ),
    ]
