# Generated by Django 3.0.8 on 2020-07-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0009_unitlayanan_unit_induk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit_induk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitInduk'),
        ),
        migrations.AddField(
            model_name='device',
            name='unit_layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitLayanan'),
        ),
        migrations.AddField(
            model_name='device',
            name='unit_pelaksana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network_automation.UnitPelaksana'),
        ),
    ]
